name: imgstore

channels:
  - loopbio
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python=2.7
  - loopbio::ffmpeg=4.0.2=nonvidia_gpl*
  - loopbio::opencv=3.4.2

  - python-dateutil
  - pytz
  - tzlocal

  - pyyaml
  - numpy
  - pandas
  - bloscpack

  - pytest
  - pytest-cov
  - pytest-pep8

  - pip:
    - "--editable=./"
