name: imgstore

channels:
  - conda-forge
  - defaults

dependencies:

  - python

  - numpy
  - pandas
  - bloscpack

  - opencv
  # - pims
  - slicerator
  - av
  - ffmpeg
  - imageio

  - ruamel.yaml

  - ipython
  - jupyter

  - pytest
  - pytest-cov
  - pytest-pep8

  - pip:
    - "--editable=./"
