name: imgstore

channels:
  - conda-forge
  - defaults

dependencies:

  - python

  - numpy
  - pandas
  - bloscpack

  - opencv

  - ruamel.yaml

  - pytest
  - pytest-cov
  - pytest-pep8

  - pip:
    - "--editable=./"
